### ISSUE TITLE
Values are no longer updated

### ISSUE THREAD

**Issue by mrbungle64** [futomi/node-switchbot#178]
### Analysis

With version 1.7.3 the values for example of the "Meter" hygrometer or a "Contact Sensor" are no longer updated using `startScan()` and `onadvertisement`.

I recognized this behavior with my [ioBroker adapter](https://github.com/mrbungle64/ioBroker.switchbot-ble) after updating to version 1.7.3 of node-switchbot and one of my contact sensors no longer responded when I closed or opened the door. Then I checked the values one of the hygrometers and the values were not updated.

I used the [example code](https://github.com/OpenWonderLabs/node-switchbot#quick-start) to reproduce it.

With version 1.7.2 the problem does not appear to exist.

### Expected Behavior

The values should update as they change.

### Steps To Reproduce

Use the [example code](https://github.com/OpenWonderLabs/node-switchbot#quick-start) to reproduce it (with a hygrometer for example).

You may have to increase the wait time:

```js
await switchbot.wait(100000);
```

and also directly pass the id of the device you want to check:

```js
switchbot.startScan({
  id: 'cb:4e:b9:03:c9:6d',
})...
```

### Environment

- OS: Raspberry Pi OS
- Node: v16.18.1
- npm: 8.19.2
- node-switchbot: 1.7.3

**Comment by mrbungle64** [comment]
@donavanbecker 

Have you already checked this?

**Comment by donavanbecker** [comment]
@mrbungle64 No, not much time right now to check. Sorry. I can merge a PR though if you find a fix.

**Comment by mrbungle64** [comment]
@donavanbecker

Am I the only one having this issue?

**Comment by donavanbecker** [comment]
I don't use BLE on meters, I can test it though.

**Comment by mrbungle64** [comment]
> I don't use BLE on meters, I can test it though.

As far as I remember contact sensors were also affected...

**Comment by donavanbecker** [comment]
My contact sensors have been working fine.

**Comment by mrbungle64** [comment]
> My contact sensors have been working fine.

Just to make sure: are you using version 1.7.3?
Please also check the @abandonware/noble version

**Comment by mrbungle64** [comment]
@donavanbecker 

With version 1.8.0 the issue still persists for me.
The values of the contact sensor and the meters are only updated once (at start/restart).

After a downgrade to version 1.7.2 it works fine again.

**Comment by mrbungle64** [comment]
@donavanbecker 

Any news on this?

**Comment by donavanbecker** [comment]
@mrbungle64 I am not experiencing the issue.

**Comment by mrbungle64** [comment]
Ok, if you don't take the reported issue seriously, I'll have to think about discontinue [my project](https://github.com/mrbungle64/ioBroker.switchbot-ble) and not buying any more SwitchBot products either.

There are 6 assignees, but all I here is something like "it works on my machine" from one of them ...
Sorry, but it annoys me right now ...

**Comment by mrbungle64** [comment]
@OpenWonderLabs

I like your products and one of the reasons I chose your products was that you also provide open source libraries.
I think that these then also deserve a little more attention in terms of support.

**Comment by donavanbecker** [comment]
I don't work for SwitchBot so if you can improve this repo, with a fix then submit it and I will merge it.

**Comment by mrbungle64** [comment]
> I don't work for SwitchBot so if you can improve this repo, with a fix then submit it and I will merge it.

@donavanbecker 

I know that you don't work for SwitchBot. That's why I mentioned that you're not the only assignee and I also posted a message addressed to @OpenWonderLabs.

**Comment by mrbungle64** [comment]
@OpenWonderLabs @SwitchBot @SwitchBot-Wonderlabs @donavanbecker 

I have so far assumed that this is the official GitHub account of SwitchBot.
Am I wrong about that?

**Comment by mrbungle64** [comment]
@donavanbecker 

It seems that (in my case) it's caused by version 1.9.2-19 of @abandonware/noble.
When I force the installation of version 1.9.2-15 the values are updated again (version 1.8.0 of node-switchbot)

**Comment by donavanbecker** [comment]
So not a SwitchBot issue. More of a raspberrypi and noble issue.

**Comment by donavanbecker** [comment]
Here you go @mrbungle64 https://github.com/abandonware/noble/issues/296

For the time being I will revert back to `-15`

**Comment by donavanbecker** [comment]
@mrbungle64, can you try the latest beta of node-switchbot?

**Comment by mrbungle64** [comment]
> @mrbungle64, can you try the latest beta of node-switchbot?

I get this error on 2 different systems:

```
Error: Cannot find module '@switchbot/noble'
```

**Comment by donavanbecker** [comment]
Sorry @mrbungle64, I have released a new beta

**Comment by mrbungle64** [comment]
@donavanbecker 

> Sorry @mrbungle64, I have released a new beta

The values are basically updated with v1.8.1-beta.9 (for several devices), but (in my case) the "Meter" (2 devices) and "Meter Plus" (1 device) are still not working, and also controlling the arm of the "Bot" devices is not working (1 device only, the battery of the 2nd device is empty).

After reverting to v1.7.2 all functions are working properly again.

**Comment by mrbungle64** [comment]
@donavanbecker @dnicolson 

#185 (updating to @abandonware/noble  version 1.9.2-20) seems to fix the original issue "Values are no longer updated", but with v1.8.1-beta.10 "Meter" and "Meter Plus" are still not working and the arm of the "Bot" device seems to work only once.

Thank you 👍🏻 I think we can close this issue.
I'll create new issues for "Meter" and "Bot" devices later.
